### ISSUE TITLE
Comparison with component/url

### ISSUE THREAD

**Issue by dandv** [kaerus-component/urlparser#2]
How does this compare to prior art like https://github.com/component/url ?

**Comment by kaerus** [comment]
The parsing is completely different, I use regular expressions that works in all .js engines. The one you are referring to works only in browsers using the DOM. I also allow other protocols than http & https so that you can use any type of url such as `ftp://user:pass@ftp.server.com`. It also handles "git styled" urls such as `git://user:pass@mygit.server.com:1234/path:myrepo`. To compare, just throw different types of urls onto each library and examine the resulting object.
